### ISSUE TITLE
While using it for the first time : problem with the use of blessed

### ISSUE THREAD

**Issue by LeSurvivants** [LucasParsy/haccks#1]
When I try to use your packages it send me this error : 

ValueError: green is not a real color, please check https://blessed.readthedocs.io/en/latest/colors.html for available colors

And here is the full error : 

Traceback (most recent call last):
  File "/home/utilisateur/PycharmProjects/pythonProject/Scraper/Tests simple sans rien.py", line 7, in <module>
    h = Haccks(len(password))
  File "/home/utilisateur/PycharmProjects/pythonProject/Scraper/venv/lib/python3.9/site-packages/haccks/__init__.py", line 43, in __init__
    self.__primaryColor = self.__checkColor(primaryColor)
  File "/home/utilisateur/PycharmProjects/pythonProject/Scraper/venv/lib/python3.9/site-packages/haccks/__init__.py", line 60, in __checkColor
    raise ValueError(
ValueError: green is not a real color, please check https://blessed.readthedocs.io/en/latest/colors.html for available colors

So w/ that I've tried to change the color, but same error (the only thing that changed was the name at the end of the error message)
Hope this is an issue from my side and you could help me with that...

**Comment by LeSurvivants** [comment]
Update : 
If I delete those line
`python
self.__primaryColor = self.__checkColor(primaryColor)`
`python
self.__secondaryColor = self.__checkColor(secondaryColor)`
it seems to work well so I think it as something to do with the use of pycharm...

**Comment by LeSurvivants** [comment]
If you get this error : execute the script into pycharm in the terminal with the command `python<version> <The name of the script>`
And not run it by pressing the green ⏯️

**Comment by LucasParsy** [comment]
Ah, it must be because the pycharm terminal does not support colors I guess. Thanks for using this library, I will update the error message to make it more useful and clear!

________________________________
